name:                dbg
version:             0.1.0.0
github:              "johannesmarti/dbg"
license:             BSD3
author:              "Johannes Marti"
maintainer:          "johannes.marti@gmail.com"
copyright:           "2022 Johannes Marti"

#extra-source-files:
#- README.md
#- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
#description:         Please see the README on GitHub at <https://github.com/githubuser/dbg#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- set-extra
- vector
- data-ordlist
- extra
- mtl
- hspec

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  dbg-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dbg

tests:
  dbg-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dbg
